version: '3.8'

volumes:
    logs:
    prometheus_data:

services:
    sir-goose:
        build:
            context: ./
        container_name: sir-goose
        env_file: ./.env
        environment:
            - NODE_ENV=production
        image: sir-goose:latest
        volumes:
            - logs:/logs/
        ports:
            - '5000:5000'
        restart: always

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        expose:
            - 9090

    promtail:
        image: grafana/promtail:2.4.1
        volumes:
            - logs:/logs/
            - ./docker/promtail/:/etc/promtail/
        command: -config.file=/etc/promtail/config.yml
