version: '3.8'

volumes:
    logs:
    prometheus_data:
    grafana_data:
    loki_data:

networks:
    grafnet:

services:
    sir-goose:
        build:
            context: ./
        container_name: sir-goose
        env_file: ./.env
        environment:
            - NODE_ENV=production
        image: sir-goose:latest
        volumes:
            - logs:/logs/
        ports:
            - '5000:5000'
        networks:
            - 'grafnet'
        restart: always

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./docker/prometheus/config.yml:/etc/prometheus/config.yml
            - prometheus_data:/var/lib/prometheus
        command:
            - '--config.file=/etc/prometheus/config.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        expose:
            - 9090
        networks:
            - 'grafnet'

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - '3000:3000'
        volumes:
            - grafana_data:/var/lib/grafana
        networks:
            - 'grafnet'

    loki:
        image: grafana/loki:latest
        container_name: loki
        volumes:
            - ./docker/loki/config.yml:/etc/loki/config.yml
            - loki_data:/var/lib/loki
        command:
            - '--config.file=/etc/loki/config.yml'
        ports:
            - '3100:3100'
        networks:
            - 'grafnet'
