services:
    sir-goose:
        image: ghcr.io/sunny-zuo/sir-goose-bot:master
        container_name: sir-goose
        hostname: sir-goose
        restart: unless-stopped
        env_file: ./.env
        environment:
            - NODE_ENV=production
        volumes:
            - type: bind
              source: ./logs
              target: /usr/src/goose/logs
            - type: bind
              source: ./src/data/verification
              target: /usr/src/goose/src/data/verification
        expose:
            - '5000'
            - '8080'

    caddy:
        image: caddy
        container_name: caddy
        hostname: caddy
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        env_file: ./docker/caddy/.env
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy-config:/config
            - caddy-storage:/data

    prometheus:
        image: prom/prometheus:v2.46.0
        container_name: prometheus
        hostname: prometheus
        user: root
        restart: unless-stopped
        depends_on:
            - cadvisor
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=90d'
            - '--web.enable-lifecycle'
        volumes:
            - prometheus-storage:/prometheus
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        expose:
            - '9090'
        labels:
            org.label-schema.group: 'monitoring'

    grafana:
        image: grafana/grafana:10.0.3
        container_name: grafana
        hostname: grafana
        user: root
        restart: unless-stopped
        volumes:
            - grafana-storage:/var/lib/grafana
        expose:
            - '3000'
        labels:
            org.label-schema.group: 'monitoring'

    nodeexporter:
        image: prom/node-exporter:v1.6.1
        container_name: nodeexporter
        hostname: nodeexporter
        restart: unless-stopped
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        expose:
            - '9100'
        labels:
            org.label-schema.group: 'monitoring'

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.47.2
        container_name: cadvisor
        hostname: cadvisor
        restart: unless-stopped
        privileged: true
        devices:
            - /dev/kmsg:/dev/kmsg
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
            - /cgroup:/cgroup:ro
        expose:
            - '8080'
        labels:
            org.label-schema.group: 'monitoring'

    loki:
        image: grafana/loki:2.7.5
        container_name: loki
        hostname: loki
        user: root
        restart: unless-stopped
        volumes:
            - loki-storage:/loki
            - ./docker/loki/loki-config.yml:/etc/loki-config.yml
        command:
            - '-config.file=/etc/loki-config.yml'
        expose:
            - '3100'
        labels:
            org.label-schema.group: 'monitoring'

    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: ['--interval', '3600', 'sir-goose']

networks:
    default:
        name: 'geese'

volumes:
    caddy-storage:
        external: true
    caddy-config:
        external: true
    grafana-storage:
        external: true
    prometheus-storage:
        external: true
    loki-storage:
        external: true
