global:
    scrape_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
          - targets: ['localhost:9090']

remote_write:
    - url: 'https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push'
      basic_auth:
