name: Deploy
on:
    push:
        branches:
            - master

    workflow_dispatch:
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node v16
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test
              
    deploy:
        name: Deploy to Azure
        runs-on: ubuntu-latest
        steps:
            - name: Update Azure Instance
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOSTNAME }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    # We relogin to ensure that our credentials are valid
                    script: |
                        cd sir-goose-bot
                        git pull
                        npm ci
                        npm run build
                        pm2 restart sir-goose-bot
